# This is a basic workflow to help you get started with Actions

name: Cleanup packages

# Controls when the workflow will run
on:
  schedule:
  - cron: "0 5 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  clean:
    strategy:
      matrix:
        package: ['ROOT.Zfs.Core', 'ROOT.Zfs.Public']
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Delete Package
        uses: actions/delete-package-versions@v3
        with: 
          package-name: ${{ matrix.package }}
          min-versions-to-keep: 10
          delete-only-pre-release-versions: "false"
